title: Juan Briceno
logo: /assets/img/juan.jpg
round-logo: true
position: A human being should be able to change a diaper, plan an invasion, butcher a hog, conn a ship, design a building, write a sonnet, balance accounts, build a wall, set a bone, comfort the dying, take orders, give orders, cooperate, act alone, solve equations, analyze a new problem, pitch manure, program a computer, cook a tasty meal, fight efficiently, die gallantly. Specialization is for insects. â€• Robert Heinlein
linkedin: https://www.linkedin.com/in/juanpablobriceno/
github_link: https://github.com/juanbric
theme: jekyll-theme-minimal
google_analytics: UA-133199451-3
